trigger:
  - master

pr:
  - master

jobs:
  - job: "Test"
    pool:
      vmImage: "Ubuntu-16.04"
    strategy:
      matrix:
        Python36_TF113:
          python.version: "3.6"
          tensorflow.version: "1.13.1"
        Python37_TF114:
          python.version: "3.7"
          tensorflow.version: "1.14.0"
          pytest.args: "--cov=larq --cov-report=html --cov-config=.coveragerc"
          docs: "true"
        Python37_TF2:
          python.version: "3.7"
          tensorflow.version: "2.0.0-beta1"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"

      - script: |
          pip install tensorflow==$(tensorflow.version)
          pip install -e .[test]
          pip install pytest-azurepipelines
        displayName: "Install dependencies"

      - script: pytest . $(pytest.args)
        displayName: "pytest"

      - script: |
          pip install nbconvert git+https://github.com/lgeiger/pydoc-markdown.git
          pip install -e .[docs]
        displayName: "Install docs dependencies"
        condition: eq(variables['docs'], 'true')

      - script: ./larqdocs.sh build
        displayName: "Build docs"
        condition: eq(variables['docs'], 'true')
