# (generated with --quick)

quantized_scope: module
tf: module

def test_distribute_scope(distribute_scope) -> None: ...
def test_eager_and_graph_mode_fixture(eager_and_graph_mode) -> None: ...
def test_eager_mode_fixture(eager_mode) -> None: ...
def test_graph_mode_fixture(graph_mode) -> None: ...
def test_quantize_scope(quantized) -> None: ...
