# (generated with --quick)

metrics: module
pytest: module
tf: module

def test_config() -> None: ...
def test_metric(eager_mode) -> None: ...
def test_metric_in_graph_mode(graph_mode) -> None: ...
def test_scope() -> None: ...
