# (generated with --quick)

import larq.models
from typing import Any, Type

ModelProfile: Type[larq.models.ModelProfile]
lq: module
np: module
pytest: module
run_around_tests: Any
tf: module

def get_profile_model() -> Any: ...
def test_bitsize_invalid_key() -> None: ...
def test_layer_profile() -> None: ...
def test_model_profile() -> None: ...
def test_number_as_readable_str_large() -> None: ...
def test_summary(snapshot, capsys) -> None: ...
def test_summary_invalid_model() -> None: ...
