# (generated with --quick)

from typing import Any

lq: module
np: module
tf: module

def _eval_helper(tensors) -> Any: ...
def _eval_tensor(tensor) -> Any: ...
def evaluate(tensors) -> Any: ...
def generate_real_values_with_zeros(low = ..., high = ..., shape = ...) -> Any: ...
def get_small_bnn_model(input_dim, num_hidden, output_dim, trainable_bn = ...) -> Any: ...
def layer_test(layer_cls, kwargs = ..., input_shape = ..., input_dtype = ..., input_data = ..., expected_output = ..., expected_output_dtype = ..., should_run_eagerly = ...) -> Any: ...
def random_input(shape) -> Any: ...
