name: Lint

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install project dependencies
        run: |
          pip install tensorflow-cpu==2.15.0
          pip install -e .[test]
      - name: Ruff format check
        run: ruff format . --check
      - name: Ruff lint check
        run: ruff check .
      - name: Type check with mypy
        run: mypy
